"""Confluence HTML export normalization (K1)."""

from src.ingest.confluence import normalize_html

_CONFLUENCE_PAGE = b"""<html><head><title>SPACE : How billing works</title></head>
<body>
<div id="page">
<div id="main-header"><div id="breadcrumb-section"><ol><li>Home</li><li>Billing</li></ol></div></div>
<h1 id="title-heading" class="pagetitle"><span id="title-text">How billing works</span></h1>
<div id="content" class="view">
<div class="page-metadata">Created by Someone, last modified on Jan 01</div>
<p>Invoices are generated monthly.</p>
</div>
<div id="footer" role="contentinfo"><section class="footer-body"><p>Document generated by Confluence on Jan 01</p></section></div>
</div>
</body></html>"""


def test_confluence_boilerplate_stripped():
    out = normalize_html(_CONFLUENCE_PAGE).decode()
    assert "Invoices are generated monthly." in out
    assert "breadcrumb-section" not in out
    assert "page-metadata" not in out
    assert "Document generated by Confluence" not in out


def test_confluence_title_preserved():
    out = normalize_html(_CONFLUENCE_PAGE).decode()
    assert "How billing works" in out


def test_non_confluence_html_untouched():
    plain = b"<html><body><h1>Hello</h1><p>World</p></body></html>"
    assert normalize_html(plain) == plain


def test_invalid_bytes_untouched():
    junk = b"\xff\xfenot html"
    assert normalize_html(junk) == junk
