"""Confluence HTML-export normalization (K1 bundle ingest).

A Confluence space export is a zip of standalone HTML pages wrapped in heavy
navigation chrome (breadcrumbs, page metadata, footer). Indexing that chrome
poisons retrieval — every page would match "Home", "Created by", etc. This
module strips the known boilerplate blocks at unpack time so the stored child
blob is already clean; downstream extraction/chunking needs no special case.

Detection is per-file and marker-based (no bundle-level state): only HTML that
carries Confluence-export ids is touched, everything else passes through
byte-identical.
"""

from __future__ import annotations

import re

# Present in Confluence HTML space exports; used only for detection.
_MARKERS = (
    b'id="breadcrumb-section"',
    b'id="title-heading"',
    b"Document generated by Confluence",
)

# Boilerplate blocks to drop. The export format nests each in a single
# div with a stable id/class, so a non-greedy DOTALL regex per block is
# sufficient and avoids a DOM dependency. Patterns intentionally match up
# to the FIRST closing </div> — the export keeps these blocks flat.
_STRIP_PATTERNS = [
    re.compile(rb'<div id="breadcrumb-section".*?</div>', re.DOTALL),
    re.compile(rb'<div class="page-metadata".*?</div>', re.DOTALL),
    re.compile(rb'<div id="footer".*?</div>', re.DOTALL),
]


def normalize_html(content: bytes) -> bytes:
    """Strip Confluence-export chrome; non-Confluence input returns unchanged."""
    if not any(m in content for m in _MARKERS):
        return content
    out = content
    for pat in _STRIP_PATTERNS:
        out = pat.sub(b"", out)
    return out
