#!/usr/bin/env bash
# Sync the bundled seed snapshot (`src/_bundled_seed/`) to a specific ref of
# the OSS seed repo. Used before a release-cut to refresh the in-wheel fallback
# that ships when no operator Initial Workspace Template is configured.
#
# Usage:
#   scripts/sync_bundled_seed.sh                       # syncs to latest tag of OSS seed
#   scripts/sync_bundled_seed.sh main                  # syncs to a specific ref
#   scripts/sync_bundled_seed.sh main https://my.fork  # syncs from a forked seed
#
# The script:
#   1. Clones the source repo (shallow) at the target ref into a tmpdir.
#   2. Copies install-prompt/ and workspace/.claude/skills/connector-*/ +
#      workspace/.claude/skills/_lib/ into src/_bundled_seed/.
#   3. Writes the provenance to src/_bundled_seed/.source_ref so the CI guard
#      at .github/workflows/check-bundled-seed.yml can verify the snapshot
#      matches a real commit.
#   4. Reports the diff. Operator commits the result manually — this script
#      never auto-commits to avoid surprising the release pipeline.
#
# Forks: pass your fork's URL as the second arg. The CI guard verifies against
# whatever URL ends up in .source_ref, so forks can ship their own bundle
# without touching this script.

set -euo pipefail

REF="${1:-}"
SOURCE_URL="${2:-https://github.com/keboola/agnes-infra-template}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUNDLED_DIR="$REPO_ROOT/src/_bundled_seed"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "==> sync_bundled_seed.sh"
echo "    source_url   = $SOURCE_URL"
echo "    target_ref   = ${REF:-<auto: latest tag>}"
echo "    bundled_dir  = $BUNDLED_DIR"
echo "    tmpdir       = $TMPDIR"

# Resolve ref if caller didn't specify one — pick the most recent tag.
if [ -z "$REF" ]; then
    echo "==> Looking up latest tag at $SOURCE_URL"
    REF="$(git ls-remote --tags --sort=-v:refname "$SOURCE_URL" \
              | awk '{print $2}' \
              | grep -v '\^{}' \
              | head -1 \
              | sed 's|refs/tags/||')"
    if [ -z "$REF" ]; then
        echo "ERROR: no tags found at $SOURCE_URL — pass a ref explicitly" >&2
        exit 1
    fi
    echo "    resolved ref = $REF"
fi

echo "==> Cloning $SOURCE_URL@$REF"
git clone --depth 1 --branch "$REF" "$SOURCE_URL" "$TMPDIR/seed" 2>&1 | tail -2
SHA="$(git -C "$TMPDIR/seed" rev-parse HEAD)"
echo "    resolved SHA = $SHA"

# Sanity: the seed must have the files we expect to bundle.
for required in install-prompt/template.md.tmpl \
                workspace/.claude/skills/connector-asana/SKILL.md \
                workspace/.claude/skills/connector-atlassian/SKILL.md \
                workspace/.claude/skills/connector-gws/SKILL.md; do
    if [ ! -f "$TMPDIR/seed/$required" ]; then
        echo "ERROR: source seed missing required file: $required" >&2
        exit 1
    fi
done

echo "==> Replacing $BUNDLED_DIR contents"
# Preserve .source_ref's structure: wipe the data dirs but keep the dir itself.
rm -rf "$BUNDLED_DIR/install-prompt" "$BUNDLED_DIR/workspace"
mkdir -p "$BUNDLED_DIR"

cp -R "$TMPDIR/seed/install-prompt" "$BUNDLED_DIR/install-prompt"
mkdir -p "$BUNDLED_DIR/workspace/.claude/skills"

# Copy each connector-*/ directory if present in source.
for connector_dir in "$TMPDIR/seed/workspace/.claude/skills/connector-"*; do
    if [ -d "$connector_dir" ]; then
        cp -R "$connector_dir" "$BUNDLED_DIR/workspace/.claude/skills/"
    fi
done

# Optional _lib/ doc (CONNECTOR_USAGE.md etc.) — ships with the bundle when
# the source seed has it.
if [ -d "$TMPDIR/seed/workspace/.claude/skills/_lib" ]; then
    cp -R "$TMPDIR/seed/workspace/.claude/skills/_lib" \
          "$BUNDLED_DIR/workspace/.claude/skills/_lib"
fi

cat > "$BUNDLED_DIR/.source_ref" <<EOF
# Provenance of the bundled seed snapshot in this wheel.
# Generated by scripts/sync_bundled_seed.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit by re-running the script, NOT by hand — the CI guard at
# .github/workflows/check-bundled-seed.yml verifies the SHA below is a real
# commit at source_url.
source_url=$SOURCE_URL
source_sha=$SHA
source_branch=$REF
EOF

echo "==> Done."
echo "    Review the diff with: git diff src/_bundled_seed"
echo "    Then commit: git add src/_bundled_seed && git commit -m 'chore: sync bundled seed to $REF'"
