"""GitHub App authentication and file-push helpers for the flea-market feature."""
from __future__ import annotations

import base64
import logging
import time
from dataclasses import dataclass
from typing import Optional

import requests

logger = logging.getLogger(__name__)

_PUBLIC_GITHUB_API = "https://api.github.com"


@dataclass
class GitHubAppConfig:
    app_id: str
    private_key_pem: str
    installation_id: str
    repo: str  # "owner/repo"
    api_url: str = _PUBLIC_GITHUB_API  # override for GitHub Enterprise


def _get_installation_token(config: GitHubAppConfig) -> str:
    """Exchange GitHub App JWT for a short-lived installation access token."""
    import jwt  # PyJWT

    now = int(time.time())
    # iat backdated 60s for clock skew; exp = iat+600 = 10 min from real issuance
    payload = {"iat": now - 60, "exp": now + 540, "iss": config.app_id}
    app_jwt = jwt.encode(payload, config.private_key_pem, algorithm="RS256")

    resp = requests.post(
        f"{config.api_url}/app/installations/{config.installation_id}/access_tokens",
        headers={
            "Authorization": f"Bearer {app_jwt}",
            "Accept": "application/vnd.github+json",
        },
        timeout=(10, 30),
    )
    resp.raise_for_status()
    return resp.json()["token"]


def _get_file_sha(token: str, repo: str, path: str, *, api_url: str = _PUBLIC_GITHUB_API) -> Optional[str]:
    """Return the blob SHA of an existing file, or None if it doesn't exist."""
    resp = requests.get(
        f"{api_url}/repos/{repo}/contents/{path}",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
        },
        timeout=(10, 30),
    )
    if resp.status_code == 404:
        return None
    if not resp.ok:
        logger.error("GitHub GET %s/%s returned %s", repo, path, resp.status_code)
    resp.raise_for_status()
    return resp.json()["sha"]


def push_file(
    token: str,
    repo: str,
    path: str,
    content: str,
    message: str,
    *,
    api_url: str = _PUBLIC_GITHUB_API,
    _retries: int = 1,
) -> None:
    """Create or update a file in the repo via the GitHub Contents API.

    Retries once on 409 Conflict (stale SHA from concurrent write).
    """
    encoded = base64.b64encode(content.encode()).decode()
    for attempt in range(_retries + 1):
        sha = _get_file_sha(token, repo, path, api_url=api_url)
        body: dict = {"message": message, "content": encoded}
        if sha is not None:
            body["sha"] = sha
        resp = requests.put(
            f"{api_url}/repos/{repo}/contents/{path}",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
            },
            json=body,
            timeout=(10, 30),
        )
        if resp.status_code == 409 and attempt < _retries:
            logger.warning("GitHub PUT %s/%s 409 conflict, retrying", repo, path)
            continue
        resp.raise_for_status()
        return


def push_skill(
    config: GitHubAppConfig,
    plugin_name: str,
    skill_name: str,
    skill_md: str,
) -> None:
    """Push SKILL.md to GitHub. Manifests are regenerated by nightly sync."""
    token = _get_installation_token(config)
    push_file(
        token, config.repo,
        f"plugins/{plugin_name}/skills/{skill_name}/SKILL.md",
        skill_md,
        f"feat: add community skill {skill_name}",
        api_url=config.api_url,
    )


def push_skill_with_pat(
    pat: str,
    repo: str,
    plugin_name: str,
    skill_name: str,
    skill_md: str,
    *,
    api_url: str = _PUBLIC_GITHUB_API,
) -> None:
    """Push SKILL.md to GitHub using a Personal Access Token."""
    push_file(
        pat, repo,
        f"plugins/{plugin_name}/skills/{skill_name}/SKILL.md",
        skill_md,
        f"feat: add community skill {skill_name}",
        api_url=api_url,
    )
