"""Scaffolder for ``.claude-plugin/marketplace-metadata.json`` (Gap 2 / #469).

A curated-marketplace maintainer should not hand-author the Agnes enrichment
file from a blank page. Everything that is *derivable* from the canonical
sources — ``marketplace.json``, each plugin's ``plugin.json``, and the
``SKILL.md`` / agent ``.md`` frontmatter — can be generated; the curator then
layers human-only content (cover photos, polished copy, sample interactions)
on top. The runtime parser lives in :mod:`src.marketplace_metadata`; this
module emits exactly the fields that parser recognises.

The hard part is the *merge*, not the derivation. A re-run must refresh what
the machine owns (a renamed skill, an edited description) without ever
clobbering what a human wrote. We classify every field:

  GEN   deterministically derived; regenerated each run.
          plugin : display_name
          skill  : display_name, invocation
          agent  : display_name, invocation
  DRAFT seeded from a canonical source as a starting point; treated exactly
        like GEN by the merge (so a human edit still wins).
          plugin : tagline        (first line of plugin.json description)
          skill  : when_to_use    (skill frontmatter ``description``)
          agent  : when_to_use    (agent frontmatter ``description``)
  KEEP  human-only; the scaffolder never writes these and passes existing
        values through untouched.
          cover_photo, video_url, category, description, use_cases,
          sample_interaction, doc_links

Merge contract (3-way; base = the value we last generated, tracked by a
content hash in a top-level ``_generated`` block):

  existing absent                          -> write derived   (fill)
  present, never generated by us           -> keep existing   (KEEP)
  present, hash == last generated          -> write derived   (regenerate)
  present, hash != last generated          -> keep existing   (human edit wins)

When a field we generated last run is no longer derivable (its upstream source
was deleted), it never appears in ``derived``, so a final cleanup pass handles
it — otherwise a stale machine value would linger and, having lost its
provenance, masquerade as human content on the next run:

  was ours, on-disk hash == last generated -> remove          (source gone)
  was ours, on-disk hash != last generated -> keep existing   (human edit wins)

``_generated`` is ignored by the runtime parser (it reads only ``plugins``),
so shipping it in the committed file is safe. It is what turns the old "keep
the enrichment file in sync with the plugins by hand" chore into "re-run the
scaffolder and read the diff" — and powers ``--check`` in CI.

This module deliberately has no ``app.`` dependency so it stays importable and
unit-testable on its own (mirrors the rule in
``src/store_guardrails/_frontmatter.py``).
"""

from __future__ import annotations

import copy
import hashlib
import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any, Dict, List, Optional, Tuple

from src.marketplace_metadata import (
    MARKETPLACE_METADATA_REL,
    read_marketplace_metadata,
)

GENERATOR_TAG = "agnes-marketplace-scaffold"
SCHEMA_VERSION = 1

# Mirrors ``src.marketplace.PLUGIN_MANIFEST_REL``. Re-declared here rather than
# imported because that module pulls in ``app.utils`` at import time, and this
# scaffolder must stay free of the app layer.
PLUGIN_MANIFEST_REL = Path(".claude-plugin") / "marketplace.json"

PLUGIN_JSON_REL = Path(".claude-plugin") / "plugin.json"

# Fields the merge owns. Everything else a curator puts in the file is KEEP and
# never touched. (Documented in the module docstring; duplicated here only as
# the set the report iterates over.)
_OWNED_STATUSES = frozenset({"generated", "regenerated", "unchanged"})

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)


class ScaffoldError(Exception):
    """Raised for unrecoverable input problems (missing / malformed
    ``marketplace.json``). The CLI turns this into a one-line error + exit 1.

    Note this is *stricter* than the runtime sync path
    (:func:`src.marketplace_metadata.read_marketplace_metadata`), which degrades
    to ``{}``. A curator running the scaffolder wants a loud failure, not a
    silently empty result.
    """


# --------------------------------------------------------------------------- #
# Frontmatter + string helpers
# --------------------------------------------------------------------------- #


def _parse_frontmatter(text: str) -> Dict[str, str]:
    """Parse a leading ``--- ... ---`` YAML-ish block into a flat dict.

    Mirrors :func:`src.marketplace_listing._parse_frontmatter` (skip blank and
    ``#`` comment lines, split each remaining line on the first ``:``, strip
    surrounding quotes). Kept local so the scaffolder doesn't have to import
    the heavier ``store_guardrails`` package just for this.
    """
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return {}
    out: Dict[str, str] = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def humanize(slug: str) -> str:
    """Turn a slug into a Title-Cased display name.

    ``"gws-onboarding"`` -> ``"Gws Onboarding"``, ``"dept-howto"`` ->
    ``"Dept Howto"``. Only the first letter of each token is upper-cased so
    internal capitals survive (``"APIClient"`` stays ``"APIClient"``). This is
    a best-effort GEN value — a curator who wants "Google Workspace Onboarding"
    just edits it, and the merge then leaves their edit alone.
    """
    parts = re.split(r"[-_\s]+", slug.strip())
    return " ".join(p[:1].upper() + p[1:] for p in parts if p)


def _first_line(text: str) -> str:
    for line in (text or "").splitlines():
        s = line.strip()
        if s:
            return s
    return ""


def _field_hash(value: Any) -> str:
    """Stable short content hash of a JSON-able value (provenance tracking)."""
    canon = json.dumps(value, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()[:16]


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------- #
# Plugin-clone enumeration
# --------------------------------------------------------------------------- #


@dataclass
class _Inner:
    """One skill or agent: its resolved name + parsed frontmatter."""

    name: str
    frontmatter: Dict[str, str]


def _enumerate_skills(plugin_root: Path) -> List[_Inner]:
    """Walk ``<plugin_root>/skills/*/SKILL.md``.

    Name resolution (frontmatter ``name``, fallback directory name) and sort
    order match :func:`src.marketplace_listing.list_inner_skills` so the
    metadata keys line up with what Agnes resolves at request time. A parity
    test pins this.
    """
    out: List[_Inner] = []
    d = plugin_root / "skills"
    if not d.is_dir():
        return out
    for skill_dir in sorted(d.iterdir()):
        if not skill_dir.is_dir():
            continue
        md = skill_dir / "SKILL.md"
        if not md.is_file():
            continue
        try:
            text = md.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm = _parse_frontmatter(text)
        name = (fm.get("name") or skill_dir.name or "").strip()
        if name:
            out.append(_Inner(name=name, frontmatter=fm))
    return out


def _enumerate_agents(plugin_root: Path) -> List[_Inner]:
    """Walk ``<plugin_root>/agents/*.md``; resolution mirrors
    :func:`src.marketplace_listing.list_inner_agents`."""
    out: List[_Inner] = []
    d = plugin_root / "agents"
    if not d.is_dir():
        return out
    for p in sorted(d.iterdir()):
        if not p.is_file() or p.suffix != ".md":
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm = _parse_frontmatter(text)
        name = (fm.get("name") or p.stem or "").strip()
        if name:
            out.append(_Inner(name=name, frontmatter=fm))
    return out


def _read_manifest(marketplace_root: Path) -> Dict[str, Any]:
    path = marketplace_root / PLUGIN_MANIFEST_REL
    if not path.is_file():
        raise ScaffoldError(f"no marketplace manifest at {path}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError as e:
        raise ScaffoldError(f"cannot read {path}: {e}") from e
    except ValueError as e:
        raise ScaffoldError(f"malformed JSON in {path}: {e}") from e
    if not isinstance(data, dict):
        raise ScaffoldError(f"{path}: top-level must be a JSON object")
    return data


def _read_plugin_json(
    plugin_root: Path,
    name: Optional[str] = None,
    report: Optional["ScaffoldReport"] = None,
) -> Dict[str, Any]:
    p = plugin_root / PLUGIN_JSON_REL
    if not p.is_file():
        # A missing plugin.json is normal — plugin-level fields then fall back
        # to the manifest entry. Only a *present but broken* file is worth a warning.
        return {}
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        if report is not None:
            report.warnings.append(
                f"plugin {name!r}: cannot read {PLUGIN_JSON_REL} ({e}) — "
                "plugin-level fields fall back to the manifest"
            )
        return {}
    if not isinstance(data, dict):
        if report is not None:
            report.warnings.append(
                f"plugin {name!r}: {PLUGIN_JSON_REL} is not a JSON object — ignored"
            )
        return {}
    return data


def _resolve_plugin_root(
    marketplace_root: Path, entry: Dict[str, Any], report: "ScaffoldReport",
) -> Optional[Path]:
    """Resolve a manifest ``plugins[].source`` to a local directory.

    Returns ``None`` (with a warning) for remote/URL sources or paths that
    escape the marketplace root — the plugin still gets plugin-level fields
    from its manifest entry, just no skill/agent enumeration.
    """
    name = entry.get("name")
    source = entry.get("source")
    if not isinstance(source, str) or not source.strip():
        # No source → plugin lives at the marketplace root (single-plugin repo).
        return marketplace_root
    s = source.strip()
    if "://" in s:
        report.warnings.append(
            f"plugin {name!r}: remote source {s!r} — skills/agents not enumerated"
        )
        return None
    rel = PurePosixPath(s.removeprefix("./"))
    if rel.is_absolute() or ".." in rel.parts:
        report.warnings.append(f"plugin {name!r}: unsafe source path {s!r} — skipped")
        return None
    root = (marketplace_root / Path(*rel.parts)).resolve()
    try:
        root.relative_to(marketplace_root.resolve())
    except ValueError:
        report.warnings.append(f"plugin {name!r}: source {s!r} escapes repo — skipped")
        return None
    if not root.is_dir():
        report.warnings.append(f"plugin {name!r}: source dir not found: {s}")
        return None
    return root


# --------------------------------------------------------------------------- #
# Derivation (GEN + DRAFT)
# --------------------------------------------------------------------------- #


def _derive_plugin(
    name: str, plugin_json: Dict[str, Any], manifest_entry: Dict[str, Any],
) -> Dict[str, str]:
    out: Dict[str, str] = {"display_name": humanize(name)}
    desc = plugin_json.get("description")
    if not isinstance(desc, str) or not desc.strip():
        desc = manifest_entry.get("description")
    tagline = _first_line(desc if isinstance(desc, str) else "")
    if tagline:
        out["tagline"] = tagline
    return out


def _derive_skill(plugin_name: str, inner: _Inner) -> Dict[str, str]:
    out: Dict[str, str] = {"display_name": humanize(inner.name)}
    invocation = f"/{plugin_name}:{inner.name}"
    arg = (inner.frontmatter.get("argument-hint") or "").strip()
    if arg:
        invocation = f"{invocation} {arg}"
    out["invocation"] = invocation
    desc = (inner.frontmatter.get("description") or "").strip()
    if desc:
        out["when_to_use"] = desc
    return out


def _derive_agent(plugin_name: str, inner: _Inner) -> Dict[str, str]:
    out: Dict[str, str] = {"display_name": humanize(inner.name)}
    out["invocation"] = f"@{plugin_name}:{inner.name}"
    desc = (inner.frontmatter.get("description") or "").strip()
    if desc:
        out["when_to_use"] = desc
    return out


# --------------------------------------------------------------------------- #
# Merge
# --------------------------------------------------------------------------- #


def _merge_field(
    section: Dict[str, Any],
    field_name: str,
    derived: Any,
    prior_hash: Optional[str],
) -> str:
    """Apply the 3-way merge for one field in-place on ``section``.

    Returns one of: ``generated`` | ``regenerated`` | ``unchanged`` |
    ``kept-human`` | ``kept-edited``. The caller records an ownership hash for
    the statuses in :data:`_OWNED_STATUSES`.
    """
    existing = section.get(field_name)
    if existing is None or existing == "":
        section[field_name] = derived
        return "generated"
    if prior_hash is None:
        # We never generated this field — a human wrote it from the start.
        return "kept-human"
    if _field_hash(existing) == prior_hash:
        if existing == derived:
            return "unchanged"
        section[field_name] = derived
        return "regenerated"
    # We generated it once, but the value changed since → a human edited it.
    return "kept-edited"


def _prior_hashes(doc: Dict[str, Any]) -> Dict[str, Dict[str, str]]:
    gen = doc.get("_generated") if isinstance(doc, dict) else None
    if not isinstance(gen, dict):
        return {}
    fields = gen.get("fields")
    if not isinstance(fields, dict):
        return {}
    out: Dict[str, Dict[str, str]] = {}
    for section_key, field_map in fields.items():
        if not isinstance(section_key, str) or not isinstance(field_map, dict):
            continue
        out[section_key] = {
            fk: fv for fk, fv in field_map.items()
            if isinstance(fk, str) and isinstance(fv, str)
        }
    return out


def _build_generated_block(
    fields: Dict[str, Dict[str, str]], generated_at: Optional[str],
) -> Dict[str, Any]:
    return {
        "by": GENERATOR_TAG,
        "schema": SCHEMA_VERSION,
        "at": generated_at or _utcnow_iso(),
        "doc": (
            "Provenance for the Agnes marketplace-metadata scaffolder: "
            "section -> {field: content-hash} for machine-generated fields. "
            "Edit a field by hand and the scaffolder stops managing it. "
            "Ignored by the runtime parser."
        ),
        "fields": {
            key: {fk: fields[key][fk] for fk in sorted(fields[key])}
            for key in sorted(fields)
        },
    }


# --------------------------------------------------------------------------- #
# Report
# --------------------------------------------------------------------------- #


@dataclass
class ScaffoldReport:
    plugins: List[str] = field(default_factory=list)
    skills: List[str] = field(default_factory=list)
    agents: List[str] = field(default_factory=list)
    actions: List[Tuple[str, str, str]] = field(default_factory=list)
    orphans: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def status_counts(self) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for _section, _field, status in self.actions:
            counts[status] = counts.get(status, 0) + 1
        return counts

    def wrote_changes(self) -> bool:
        """True when the merge wrote, refreshed, or removed a machine value."""
        return any(
            status in ("generated", "regenerated", "removed")
            for _section, _field, status in self.actions
        )


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #


def _apply_section(
    section: Dict[str, Any],
    derived: Dict[str, Any],
    prior: Dict[str, str],
    new_gen: Dict[str, Dict[str, str]],
    section_key: str,
    report: ScaffoldReport,
) -> None:
    for field_name, derived_value in derived.items():
        status = _merge_field(section, field_name, derived_value, prior.get(field_name))
        report.actions.append((section_key, field_name, status))
        if status in _OWNED_STATUSES:
            new_gen.setdefault(section_key, {})[field_name] = _field_hash(
                section[field_name]
            )
    # Fields we generated last run but no longer derive (the upstream source
    # text was removed). Clean them up so a stale value can't linger and then,
    # provenance lost, get mistaken for human content on the next run.
    for field_name, prior_hash in prior.items():
        if field_name in derived or field_name not in section:
            continue
        if _field_hash(section[field_name]) == prior_hash:
            del section[field_name]
            report.actions.append((section_key, field_name, "removed"))
        else:
            report.actions.append((section_key, field_name, "kept-edited"))


def scaffold_metadata(
    marketplace_root: Path,
    *,
    existing: Optional[Dict[str, Any]] = None,
    generated_at: Optional[str] = None,
) -> Tuple[Dict[str, Any], ScaffoldReport]:
    """Build / refresh the marketplace-metadata document for a cloned repo.

    ``marketplace_root`` is a checkout containing ``.claude-plugin/
    marketplace.json``. ``existing`` defaults to whatever
    :func:`read_marketplace_metadata` finds on disk; pass it explicitly for a
    pure merge (tests). ``generated_at`` overrides the ``_generated.at``
    timestamp for reproducible output.

    Returns ``(document, report)``. The document is ready to serialise with
    :func:`render_document`; KEEP fields and unknown keys in ``existing`` are
    preserved verbatim.
    """
    manifest = _read_manifest(marketplace_root)
    plugin_entries = manifest.get("plugins")
    if not isinstance(plugin_entries, list):
        raise ScaffoldError("marketplace.json: 'plugins' must be an array")

    if existing is None:
        existing = read_marketplace_metadata(marketplace_root)
    doc: Dict[str, Any] = copy.deepcopy(existing) if existing else {}
    prior = _prior_hashes(doc)

    out_plugins = doc.get("plugins")
    if not isinstance(out_plugins, dict):
        out_plugins = {}

    report = ScaffoldReport()
    new_gen: Dict[str, Dict[str, str]] = {}
    discovered: List[str] = []

    for entry in plugin_entries:
        if not isinstance(entry, dict):
            continue
        pname = entry.get("name")
        if not isinstance(pname, str) or not pname.strip():
            continue
        pname = pname.strip()
        discovered.append(pname)

        plugin_root = _resolve_plugin_root(marketplace_root, entry, report)
        plugin_json = (
            _read_plugin_json(plugin_root, pname, report) if plugin_root else {}
        )

        section = out_plugins.get(pname)
        if not isinstance(section, dict):
            section = {}

        pkey = f"plugins/{pname}"
        _apply_section(
            section, _derive_plugin(pname, plugin_json, entry),
            prior.get(pkey, {}), new_gen, pkey, report,
        )

        if plugin_root is not None:
            _merge_inner(
                section, "skills", _enumerate_skills(plugin_root),
                pname, _derive_skill, prior, new_gen, report,
            )
            _merge_inner(
                section, "agents", _enumerate_agents(plugin_root),
                pname, _derive_agent, prior, new_gen, report,
            )

        out_plugins[pname] = section
        report.plugins.append(pname)

    # Sections present in the file but no longer in the manifest are kept
    # (never delete a curator's data) and surfaced as orphans.
    for pname in out_plugins:
        if pname not in discovered:
            report.orphans.append(f"plugins/{pname}")

    doc["plugins"] = out_plugins
    doc["_generated"] = _build_generated_block(new_gen, generated_at)
    return doc, report


def _merge_inner(
    plugin_section: Dict[str, Any],
    kind: str,
    inners: List[_Inner],
    plugin_name: str,
    derive,
    prior: Dict[str, Dict[str, str]],
    new_gen: Dict[str, Dict[str, str]],
    report: ScaffoldReport,
) -> None:
    existing_map = plugin_section.get(kind)
    if not isinstance(existing_map, dict):
        existing_map = {}
    if not inners:
        # Nothing discovered on disk. Anything still in the file means the whole
        # skills/agents set was removed upstream — report each as an orphan
        # (consistent with partial removal) but leave the data untouched.
        for inner_name in existing_map:
            report.orphans.append(f"plugins/{plugin_name}/{kind}/{inner_name}")
        return
    out_map: Dict[str, Any] = {}
    for inner in inners:
        inner_section = existing_map.get(inner.name)
        if not isinstance(inner_section, dict):
            inner_section = {}
        ikey = f"plugins/{plugin_name}/{kind}/{inner.name}"
        _apply_section(
            inner_section, derive(plugin_name, inner),
            prior.get(ikey, {}), new_gen, ikey, report,
        )
        out_map[inner.name] = inner_section
        (report.skills if kind == "skills" else report.agents).append(ikey)
    # Preserve inner sections present in the file but not on disk (orphans).
    for inner_name, inner_section in existing_map.items():
        if inner_name not in out_map:
            out_map[inner_name] = inner_section
            report.orphans.append(f"plugins/{plugin_name}/{kind}/{inner_name}")
    plugin_section[kind] = out_map


# --------------------------------------------------------------------------- #
# Serialisation / comparison (used by the CLI)
# --------------------------------------------------------------------------- #


def render_document(doc: Dict[str, Any]) -> str:
    """Serialise to the on-disk JSON form (2-space indent, trailing newline,
    insertion order preserved so diffs are readable)."""
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def comparable_view(doc: Dict[str, Any]) -> str:
    """Canonical view of the parts that matter for ``--check`` — ``plugins``
    plus the ``_generated.fields`` provenance, excluding the volatile
    ``_generated.at`` timestamp so a no-op re-run compares equal."""
    d = doc if isinstance(doc, dict) else {}
    gen = d.get("_generated")
    gen_fields = gen.get("fields") if isinstance(gen, dict) else None
    view = {
        "plugins": d.get("plugins", {}),
        "_generated_fields": gen_fields if isinstance(gen_fields, dict) else {},
    }
    return json.dumps(view, sort_keys=True, ensure_ascii=False)


__all__ = [
    "GENERATOR_TAG",
    "SCHEMA_VERSION",
    "MARKETPLACE_METADATA_REL",
    "ScaffoldError",
    "ScaffoldReport",
    "humanize",
    "scaffold_metadata",
    "render_document",
    "comparable_view",
]
